apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-watcher-deployment
  namespace: peaks
  labels:
    app: load-watcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: load-watcher
  template:
    metadata:
      labels:
        app: load-watcher
    spec:
      containers:
      - name: load-watcher
        image: quay.io/husky_parul/load_watcher:latest
        env:
        - name: LOG_LEVEL
          value: "DEBUG"
        - name: METRICS_PROVIDER_NAME
          value: Prometheus
        - name: METRICS_PROVIDER_ADDRESS
          value: http://prometheus-k8s.monitoring.svc.cluster.local:9090
        ports:
        - containerPort: 2020
---
apiVersion: v1
kind: Service
metadata:
  namespace: peaks
  name: load-watcher
  labels:
    app: load-watcher
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 2020
    targetPort: 2020
    protocol: TCP
  selector:
    app: load-watcher
