apiVersion: kubescheduler.config.k8s.io/v1beta1
kind: KubeSchedulerConfiguration
leaderElection:
  leaderElect: false
profiles:
- schedulerName: trimaran
  plugins:
    score:
      disabled:
      - name: NodeResourcesBalancedAllocation
      - name: NodeResourcesLeastAllocated
      enabled:
      - name: TargetLoadPacking
  pluginConfig:
    - name: TargetLoadPacking
      args:
        defaultRequests:
          cpu: "2000m"
        defaultRequestsMultiplier: "2"
        targetUtilization: 70
        watcherAddress: http://load-watcher.peaks.svc.cluster.local:2020