apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: stress-ng-test
  namespace: parul
  labels:
    k8s-app: stress-ng-test
spec:
  selector:
    matchLabels:
      name: stress-ng-test
  template:
    metadata:
      labels:
        name: stress-ng-test
    spec:
      tolerations:
      # these tolerations are to have the daemonset runnable on control plane nodes
      # remove them if your control plane nodes should not run pods
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
      - name: stress-ng-test
        image: docker.io/felixgeorge/stress-ng:latest
        args: ["--cpu", "1", "--cpu-method", "float", "-t", "1000s"]
        volumeMounts:
        - name: varlog
          mountPath: /var/log
      # it may be desirable to set a high priority class to ensure that a DaemonSet Pod
      # preempts running Pods
      # priorityClassName: important
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
