apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-query-config
data:
  # Prometheus server URL
  PROMETHEUS_URL: "http://prometheus-server:9090/api/v1/query_range"

  # Start and end times for querying Prometheus
  START_TIME: "2024-09-04T00:00:00Z"
  END_TIME: "2024-09-04T12:00:00Z"

  # Directory to store the CSV files (mounted from PVC)
  CSV_DIRECTORY: "/mnt/pvc/"

  # List of metrics to query, as a comma-separated string
  METRICS_LIST: 'kepler_node_dram_joules_total,kepler_node_other_joules_total,kepler_node_package_joules_total,kepler_node_platform_joules_total,node_cpu_seconds_total'

  # Optional: Query interval (time between queries in seconds)
  QUERY_INTERVAL: "60"
