apiVersion: v1
kind: ConfigMap
metadata:
  name: stress-ng-config
data:
  # Configurable parameters for Stress-ng
  MAX_CPU_LOAD: "100"
  STEP: "10"
  DURATION: "300"
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: stress-ng-daemonset
  labels:
    app: stress-ng
spec:
  selector:
    matchLabels:
      app: stress-ng
  template:
    metadata:
      labels:
        app: stress-ng
    spec:
      containers:
      - name: stress-ng
        image: quay.io/husky_parul/stress-ng-container:latest
        args: []
        env:
        - name: MAX_CPU_LOAD
          valueFrom:
            configMapKeyRef:
              name: stress-ng-config
              key: MAX_CPU_LOAD
        - name: STEP
          valueFrom:
            configMapKeyRef:
              name: stress-ng-config
              key: STEP
        - name: DURATION
          valueFrom:
            configMapKeyRef:
              name: stress-ng-config
              key: DURATION
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      nodeSelector:
        kubernetes.io/os: linux
      restartPolicy: Always
